lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # user_identity_field: email
    api_platform:
        check_path: /auth
        username_path: email
        password_path: password

    remove_token_from_body_when_cookies_used: true

    set_cookies:
        BEARER:
            lifetime: 2592000 # set same as refresh to get good error message { "code": 401, "message": "Expired JWT Token" }
            # samesite: none
            # path: /
            domain: '%env(COOKIE_DOMAIN)%'
            # secure: false # (default to true)
            # httpOnly: true

         # token extraction settings
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
           enabled: false
        # check token in a cookie
        cookie:
            enabled: true
            name:    BEARER
